---
apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: cluster-inventory
spec:
  reportType: inventory
  schedule: '*/30 * * * *'

---
# template for network-access report. For more info https://docs.tigera.io/compliance/compliance-reports/compliance-managed-cloud#enable-audit-logs-in-eks
#
#apiVersion: projectcalico.org/v3
#kind: GlobalReport
#metadata:
#  name: cluster-network-access
#spec:
#  reportType: network-access
#  schedule: '*/30 * * * *'
#
---
 apiVersion: projectcalico.org/v3
 kind: GlobalReport
 metadata:
   name: cluster-policy-audit
 spec:
   reportType: policy-audit
   schedule: '*/30 * * * *'